# Generated by Django 3.2.6 on 2022-02-11 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('td_id', models.AutoField(primary_key=True, serialize=False)),
                ('td_thing', models.CharField(max_length=50)),
                ('td_start', models.TimeField()),
                ('td_end', models.TimeField()),
                ('task', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.task')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day_code', models.CharField(max_length=2)),
                ('todolist_id', models.ManyToManyField(blank=True, to='schedule.Todolist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
